---

- name: install apache
  hosts: linux
  become: true

  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted 

    - name: restart memcached
      service:
        name: memcached
        state: restarted

  tasks:

    - name: add an ENV variable to remote user shell
      lineinfile: 
        dest: "~/.bash_profile"
        regexp: '^ENV_VAR='
        line: 'ENV_VAR=value' 
      become: false

    - name: ensure apache is installed
      yum:
        name: httpd
        state: present

    - name: copy test config file
      copy:
        src: apachetest.conf
        dest: /etc/httpd/conf.d/apachetest.conf
      notify: 
        - restart apache
        - restart memcached

    #- name: ensure handlers flush immediately
    #  meta: flush_handlers

    - name: ensure apache is started
      service:
        name: httpd
        state: started
        enabled: true


