---

- name: install apache
  hosts: all
  become: true

 # vars_files:
 #   - apache_default.yml
 #   - apache_RedHat.yml

  handlers:
    - name: restart apache
      service:
        name: "{{ apache_package }}"
        state: restarted 

    - name: restart memcached
      service:
        name: memcached
        state: restarted
  
  pre_tasks:
    - name: load var files 
      include_vars: "{{ item }}"
      with_first_found:
        - "apache_{{ ansible_os_family }}.yml"
        - apache_default.yml


  tasks:
    - name: ensure apache is installed
      package:
        name: "{{ apache_package }}"
        state: present

    - name: copy test config file
      copy:
        src: apachetest.conf
        dest: "{{ apache_config_dir }}"
      notify: 
        - restart apache
        - restart memcached

    #- name: ensure handlers flush immediately
    #  meta: flush_handlers

    - name: ensure apache is started
      service:
        name: "{{ apache_service }}"
        state: started
        enabled: true


